export const APP_MESSAGES = {
  TYPING_HEADING: "Type at least 3 characters , example - ten , fra ",
  NO_RESULTS: "No Results",
};
export const TERMINOLOGY_API_ENDPOINT =
  "https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/SNOMEDCT-US/2022-09-01/descriptions?&limit=${LIMIT_VALUE}&term=${SEARCH_TERM_VALUE}&active=true&conceptActive=true&lang=english&groupByConcept=true";

export const TERMINOLOGY_TAG_API_ENDPOINT =
  "https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/SNOMEDCT-US/2022-09-01/descriptions?&limit=${LIMIT_VALUE}&term=${SEARCH_TERM_VALUE}&semanticTags=${TAGS}&active=true&conceptActive=true&lang=english&groupByConcept=true";
export const LENS_API_ENDPOINT = `https://lens-blitz.xcaliberapis.com`;
export const XCHANGE_SERVICE_ENDPOINT = `https://xchange-blitz.xcaliberapis.com`;
export const BUTTON_LABELS = {
  RUN: "Run",
  EDIT_PROFILE: "Edit Profile",
  UPCOMING_APPOINTMENTS: "Upcoming Appointments",
  VITALS: "Vitals",
  ALLERGIES: "Allergies",
  PROBLEMS: "Problems",
  IMMUNIZATIONS: "Immunizations",
  MEDICATIONS: "Medications",
};
export const DEPARTMENT_ID = "150";

export const DEPARTMENTS = [
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "GA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "ROME",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "34.25597",
    fax: "(207) 555-5556",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "1",
    address: "501 Broad Street",
    placeofservicetypeid: "11",
    longitude: "-85.17026",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Rome Office",
    chartsharinggroupid: "42",
    name: "Rome Office",
    placeofservicetypename: "OFFICE",
    phone: "(207) 323-7598",
    zip: "30161-3096",
    timezonename: "America/New_York",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "GA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "CARTERSVILLE",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "34.1649",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "21",
    address: "1 NORTH ERWIN STREET",
    placeofservicetypeid: "11",
    longitude: "-84.79669",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Cartersville Office-",
    chartsharinggroupid: "42",
    name: "Cartersville Office",
    placeofservicetypename: "OFFICE",
    zip: "30120-3121",
    timezonename: "America/New_York",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "2",
    state: "MA",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "BLACKSTONE VALLEY MEDICAL GROUP",
    doesnotobservedst: false,
    departmentid: "62",
    address: "1 Main St",
    placeofservicetypeid: "11",
    federaltaxid: "021234567",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Blackstone Valley",
    chartsharinggroupid: "43",
    name: "Blackstone Valley",
    placeofservicetypename: "OFFICE",
    zip: "02472-2782",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "FL",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "ORLANDO",
    placeofservicefacility: false,
    servicedepartment: true,
    fax: "(123) 456-7890",
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "82",
    address: "123 Main St",
    placeofservicetypeid: "11",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Six Hills",
    chartsharinggroupid: "41",
    name: "6 Hills",
    placeofservicetypename: "OFFICE",
    phone: "(617) 402-1234",
    clinicalproviderfax: "(701) 712-4273",
    zip: "32805-0001",
    timezonename: "America/New_York",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "CO",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "DENVER",
    placeofservicefacility: true,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "102",
    placeofservicetypeid: "22",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Cardiology Consults for 7 Hills",
    chartsharinggroupid: "42",
    name: "CARDIOLOGY",
    placeofservicetypename: "ON CAMPUS-OUTPATIENT HOSPITAL",
    address2: "100 MAIN ST",
    zip: "80218-1234",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "2",
    state: "CT",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "NEW HAVEN",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "BLACKSTONE VALLEY MEDICAL GROUP",
    doesnotobservedst: false,
    departmentid: "142",
    address: "47 COLLEGE ST.",
    placeofservicetypeid: "11",
    federaltaxid: "021234567",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Patient Face Name Test Department 47 College St",
    chartsharinggroupid: "43",
    name: "Test Department",
    placeofservicetypename: "OFFICE",
    zip: "06510-3209",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "42",
    state: "MA",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "5 Peaks Medical Organization",
    doesnotobservedst: false,
    departmentid: "143",
    federaltaxid: "021234567",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "5 Peaks",
    chartsharinggroupid: "41",
    name: "5 Peaks",
    zip: "02472-1234",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "ME",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "144",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "NonCommunicator",
    chartsharinggroupid: "42",
    name: "NonCommunicator",
    zip: "04915-0000",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "ME",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "44.41919",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "145",
    address: "2 Maine St.",
    placeofservicetypeid: "11",
    longitude: "-69.02124",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Shawnee Mission Health",
    chartsharinggroupid: "42",
    name: "Belfast Test",
    placeofservicetypename: "OFFICE",
    phone: "(207) 323-7100",
    zip: "04915-6878",
    timezonename: "America/New_York",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "42",
    state: "ME",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "5 Peaks Medical Organization",
    doesnotobservedst: false,
    departmentid: "147",
    federaltaxid: "021234567",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Ohio Health Primary Care Pickerington Office 1234",
    chartsharinggroupid: "41",
    name: "Ohio Health Primary Care Pickerington",
    zip: "04915-0001",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "NY",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "QUEENSBURY",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "44.27192",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "148",
    placeofservicetypeid: "11",
    longitude: "-69.37563",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Patient Face Name Test Department 47 College St",
    chartsharinggroupid: "42",
    name: "Testing Dept",
    placeofservicetypename: "OFFICE",
    phone: "(617) 402-1000",
    zip: "12804-0001",
    timezonename: "America/New_York",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "MA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "BOSTON",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "149",
    address: "100 Legends Way",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Psych OP",
    chartsharinggroupid: "81",
    name: "Psych OP",
    zip: "02114-0574",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "NY",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "NEW YORK",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "44.419193",
    fax: "(617) 402-1111",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "150",
    address: "5 Hatley Road",
    placeofservicetypeid: "11",
    longitude: "-69.021307",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "7 Hills Med Group",
    chartsharinggroupid: "42",
    name: "7 Hills Department",
    placeofservicetypename: "OFFICE",
    phone: "(617) 402-1111",
    address2: "suite 1",
    zip: "10021-0001",
    timezonename: "America/New_York",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "62",
    state: "MA",
    portalurl: "www.kenneth.net",
    city: "ARLINGTON",
    placeofservicefacility: false,
    servicedepartment: true,
    fax: "6174293243",
    providergroupname: "kate PG",
    doesnotobservedst: false,
    departmentid: "155",
    address: "56 Cleveland St.",
    placeofservicetypeid: "33",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Kate Smith Internalist",
    chartsharinggroupid: "41",
    name: "Kate Smith Internalist",
    placeofservicetypename: "CUSTODIAL CARE FACILITY",
    phone: "6174293243",
    zip: "02474-6916",
    timezonename: "America/Chicago",
    communicatorbrandid: "43",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -8,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "MA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "33.12390285",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "157",
    address: "1234 Hello Avenue",
    placeofservicetypeid: "11",
    longitude: "-84.29847983",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -8,
    patientdepartmentname: "CommOpsDevTest",
    chartsharinggroupid: "42",
    name: "CommOpsDevTest",
    placeofservicetypename: "OFFICE",
    zip: "02472-2805",
    timezonename: "America/Los_Angeles",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "ME",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "158",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "Test Belfast",
    chartsharinggroupid: "41",
    name: "Test Belfast",
    zip: "04915-0010",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "MA",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "42.3709299",
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "159",
    address: "400 Lombardi Way",
    longitude: "-71.1828321",
    clinicals: "OFF",
    timezone: -5,
    patientdepartmentname: "Lombardi Office",
    chartsharinggroupid: "41",
    name: "Lombardi Office",
    phone: "(555) 262-7432",
    zip: "02472-1234",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "MA",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "42.3709299",
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "160",
    address: "1 Heisman Drive",
    longitude: "-71.1828321",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Heisman Office",
    chartsharinggroupid: "41",
    name: "Heisman Office",
    phone: "(555) 212-6789",
    zip: "02472-2672",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "NY",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "NEW YORK",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "43.3760874",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "162",
    address: "122 East St",
    placeofservicetypeid: "11",
    longitude: "-73.6351245",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -5,
    patientdepartmentname: "Main Office - NY",
    chartsharinggroupid: "42",
    name: "MAIN OFFICE - NY",
    placeofservicetypename: "OFFICE",
    zip: "10021-0001",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "ME",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    fax: "(617) 402-1000",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "163",
    address: "311 Arsenal Street",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Seven Hills rholaday test ISE",
    chartsharinggroupid: "42",
    name: "athenaHealth",
    zip: "04915-6878",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "2",
    state: "ME",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "BLACKSTONE VALLEY MEDICAL GROUP",
    doesnotobservedst: false,
    departmentid: "164",
    placeofservicetypeid: "11",
    federaltaxid: "021234567",
    clinicals: "OFF",
    timezone: -5,
    patientdepartmentname: "Internal Medical Associates",
    chartsharinggroupid: "43",
    name: "Internal Medical Associates",
    placeofservicetypename: "OFFICE",
    zip: "04915-9856",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "NY",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "SCHENECTADY",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "165",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "test",
    chartsharinggroupid: "41",
    name: "test",
    zip: "12345-6789",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "MA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "42.3634917",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "166",
    address: "311 Arsenal St.",
    placeofservicetypeid: "11",
    longitude: "-71.1670094",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -5,
    patientdepartmentname: "Training Dept Patient Facing Name",
    chartsharinggroupid: "42",
    name: "Training Dept",
    placeofservicetypename: "OFFICE",
    zip: "02472-2782",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "MA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "DEDHAM",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "168",
    address: "123 Main St.",
    placeofservicetypeid: "11",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -5,
    patientdepartmentname: "Springfield Medical",
    chartsharinggroupid: "42",
    name: "Springfield Medical",
    placeofservicetypename: "OFFICE",
    zip: "02026-2217",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "MA",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    latitude: "42.3675294",
    fax: "(123) 456-7890",
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "169",
    address: "123 Main St",
    longitude: "-71.1869661",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "16, 11 testing",
    chartsharinggroupid: "42",
    name: "16.11 Testing",
    phone: "(123) 456-7890",
    zip: "02472-2783",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "KS",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "KANSAS CITY",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "170",
    address: "123 Main St",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "6 Hills Medical Group",
    chartsharinggroupid: "42",
    name: "athenaclinic",
    phone: "(333) 555-1212",
    zip: "66103-0001",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "FL",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "JACKSONVILLE",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "171",
    address: "3 Arsenal Way",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "FL Dept",
    chartsharinggroupid: "42",
    name: "FL Dept",
    phone: "(617) 402-1000",
    zip: "32212-0001",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "142",
    state: "TX",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "BUDA",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "HCP TIN Consolidation",
    doesnotobservedst: false,
    departmentid: "180",
    address: "12 main",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "HCP TIN",
    chartsharinggroupid: "41",
    name: "HCP TIN",
    zip: "78610-2775",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "2",
    state: "MA",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "WATERTOWN",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "BLACKSTONE VALLEY MEDICAL GROUP",
    doesnotobservedst: false,
    departmentid: "181",
    address: "1 Arsenal St.",
    federaltaxid: "021234567",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "Grantville Family Care",
    chartsharinggroupid: "43",
    name: "Grantville Family Care",
    phone: "617-402-1000",
    address2: "Watertown",
    zip: "02472-3649",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "MI",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "AUBURN HILLS",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "183",
    address: "5 Main Street",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Michigan Test",
    chartsharinggroupid: "42",
    name: "Michigan Test",
    zip: "48326-2757",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "ME",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "SEARSMONT",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "184",
    address: "226 New England Road",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "Angela L Crawford",
    chartsharinggroupid: "41",
    name: "Angela L Crawford",
    phone: "2079309229",
    zip: "04973-0000",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "22",
    state: "ME",
    portalurl: "https://1959-1.portal.athenahealth.com/",
    city: "BELFAST",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "6 Hills Medical Associates",
    doesnotobservedst: false,
    departmentid: "185",
    address: "3 Hatley Rd",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "Ashley's Department",
    chartsharinggroupid: "41",
    name: "Ashley's Department",
    phone: "2076156693",
    zip: "04915-1234",
    timezonename: "America/Chicago",
    communicatorbrandid: "21",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "TX",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "AUSTIN",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "192",
    address: "800 W Cesar Chavez St",
    federaltaxid: "123456789",
    clinicals: "ON",
    timezone: -6,
    patientdepartmentname: "Care Health Pediatrics",
    chartsharinggroupid: "42",
    name: "Pediatrics",
    zip: "78701-0007",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -6,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "TN",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "PARIS",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "194",
    address: "196 CARMEN DR",
    placeofservicetypeid: "11",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -6,
    patientdepartmentname: "South Dental",
    chartsharinggroupid: "42",
    name: "South Dental",
    placeofservicetypename: "OFFICE",
    phone: "4255821232",
    zip: "38242-7082",
    timezonename: "America/Chicago",
    communicatorbrandid: "1",
  },
  {
    medicationhistoryconsent: false,
    timezoneoffset: -5,
    ishospitaldepartment: false,
    providergroupid: "1",
    state: "NY",
    portalurl: "1959-1.portal.athenahealth.com",
    city: "BROOKLYN",
    placeofservicefacility: false,
    servicedepartment: true,
    providergroupname: "7 Hills Medical Group",
    doesnotobservedst: false,
    departmentid: "195",
    address: "1st line",
    federaltaxid: "123456789",
    clinicals: "OFF",
    timezone: -5,
    patientdepartmentname: "Fold Test",
    chartsharinggroupid: "42",
    name: "Fold Test",
    zip: "11201-0001",
    timezonename: "America/New_York",
    communicatorbrandid: "1",
  },
];

export const ElationAllergyValues = [
  {
    code: "unknown",
  },
  {
    code: "mild",
  },
  {
    code: "moderate",
  },
  {
    code: "severe",
  },
];
